#!/bin/bash
# Команды для добавления карточек в roxy
#
./build/roxy add_card 'はじめまして' 'Позвольте представиться'
./build/roxy add_card 'よろしくおねがいします' 'Надеюсь на ваше хорошее отношение'
./build/roxy add_card 'おはよう' 'Доброе утро! (близким)'
./build/roxy add_card 'おはようございます' 'Доброе утро! (вежливо)'
./build/roxy add_card 'こんにちは' 'Добрый день!'
./build/roxy add_card 'こんばんは' 'Добрый вечер!'
./build/roxy add_card 'さようなら' 'До свидания! Прощай (если знаем, что долго не увидимся с человеком)'
./build/roxy add_card 'それではまた' 'До встречи! (чуть более вежливо)'
./build/roxy add_card 'じゃまた' 'До встречи! (менее вежливо)'
./build/roxy add_card 'またね' 'До встречи! Увидимся (для неформального общения)'
./build/roxy add_card 'またあした' 'До завтра!'
./build/roxy add_card 'またらいしゅう' 'До следующей недели!'
./build/roxy add_card 'しつれいします' 'Извините, что вас беспокою'
./build/roxy add_card 'おさきにしつれいします' 'Извините, что ухожу раньше вас!'
./build/roxy add_card 'おつかれさまです' 'Вы сегодня хорошо поработали! (До свидания)'
./build/roxy add_card 'おげんきですか' 'Как (ваши) дела?'
./build/roxy add_card 'げんきです' 'Хорошо'
./build/roxy add_card 'だいじょうぶです' 'Нормально'
./build/roxy add_card 'まあまあです' 'Пойдет, 50/50'
./build/roxy add_card 'おかげさまでげんきです' 'Вашими молитвами, у меня все хорошо'
./build/roxy add_card 'いろいろたいへんです' 'Есть (в жизни) разные сложности'
./build/roxy add_card 'いろいろあってね' 'Всякое бывает / это долгая история'
./build/roxy add_card 'じゅうにさい' '12 лет'
./build/roxy add_card 'いっさい' '1 год'
./build/roxy add_card 'ななさい' '7 лет'
./build/roxy add_card 'はっさい' '8 лет'
